### ISSUE TITLE
[link]:  git-auto-commit-action

### ISSUE THREAD

**Issue by soker90** [soker90/issue-link#23]
### --> Enlace

https://github.com/stefanzweifel/git-auto-commit-action

### --> Descripción

Automatically commit and push changed files back to GitHub 

### --> Cuerpo

```yaml
  - name: Add prices
    id: auto-commit-action
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: 'Add report for today'
 
  - name: "Send to telegram if changes have been detected"
    if: steps.auto-commit-action.outputs.changes_detected == 'true'
    run: npm run send
```
